http:
  routers:
    whoami:
      middlewares:
        - esi
      entrypoints:
        - http
      service: whoami
      rule: Host(`domain.com`)

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami
        passHostHeader: false

  middlewares:
    esi:
      plugin:
        esi: {}